@startuml

<style>
document {
	BackgroundColor #393939
	LineColor #E8E6DF
	FontColor #E8E6DF
	FontName Roboto
	Padding 10px
}

.success {
  LineColor #99cc99
}

.neutral {
  LineColor #6699cc
}

.failure {
  LineColor #f2777a
}
</style>

participant "client-A"
queue database
participant "client-B"

"client-A" -> database <<neutral>>: start transaction
note left: t1
"client-B" -> database <<neutral>>: start transaction

"client-B" <<-- database: read empty owner 
"client-A" <<-- database: read empty owner

"client-A" -->> database: write client-A is owner
"client-B" -->> database: write client-B is owner

"client-B" -> database <<success>>: commit is accepted
"client-A" -X database <<failure>>: commit is rejected 
note left: t2

"client-A" -> database <<neutral>>: start transaction
"client-A" <<-- database: read client-B is owner
"client-A" -->> database: enqueue client-A
"client-A" -> database <<success>>: commit is accepted

@enduml
